GET http://localhost:5050/users

####

GET http://localhost:5050/users/653fa05158e6cebb04d174d8

####

POST http://localhost:5050/users/create
Content-Type: application/json

{
    "nome": "Pippo",
    "cognome": "De Pippus",
    "email": "depippus@gmail.com",
    "avatar": "",
    "password": "passwordDiProva"
}

####

GET http://localhost:5050/products

####

POST http://localhost:5050/login
Content-Type: application/json

{
    "email" : "abcapon89@gmail.com",
    "password" : "CicciPicci"
}

####
GET http://localhost:5050/blog

####
POST http://localhost:5050/blog/create
Content-Type: application/json

{
    "title" : "avatar",
    "category" : "fantasy",
    "content" : "tutto fa mucio",
    "cover" : "",
    "author" : "6542506aa62ed9100e3c1f72"
}

####
POST http://localhost:5050/create-payment-intent
Content-Type: application/json

{
  "items": [
    { "price": 10,
    "name" : "CicciPicci" },
    { "price" : 20,
    "name" : "Pippo"}
  ]
}